### ISSUE TITLE
mutation throwing shared permission exception

### ISSUE THREAD

**Issue by bappajubcse05** [yahoo/elide#754]
I have two tables with 1 to many relationship: Parent and child 
I have one existing parent record with id: 1

when I am trying to insert a new child using below query-

```
mutation {
  parent(filter: "id==1") {
    edges {
      node {
        id
        childs(op: UPSERT, data: {id: "b5aab819-4a31-41e0-a878-62a980e5e702", name: "test", status: "New"}) {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
```

It is throwing below exception:

```
{
  "data": null,
  "errors": [
    {
      "message": "Exception while fetching data (/parent/edges[0]/node/childs) : null",
      "path": [
        "parent",
        "edges",
        0,
        "node",
        "childs"
      ],
      "exception": {
        "cause": null,
        "stackTrace": [],
        "status": 403,
        "expression": {
          "present": true
        },
        "evaluationMode": {
          "present": true
        },
        "loggedMessage": "ForbiddenAccessException: Message=SharePermission: \u001b[31mFAILURE\u001b[m\tMode=Optional[USER_CHECKS_ONLY]\tExpression=[Optional[\u001b[31mFAILURE\u001b[m]]",
        "verboseMessage": "SharePermission: \u001b[31mFAILURE\u001b[m",
        "verboseErrorResponse": {
          "403": {
            "errors": [
              "SharePermission: \u001b[31mFAILURE\u001b[m"
            ]
          }
        },
        "errorResponse": {
          "403": {
            "errors": [
              "ForbiddenAccessException"
            ]
          }
        },
        "localizedMessage": null,
        "message": null,
        "suppressed": []
      },
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ],
      "extensions": null,
      "errorType": "DataFetchingException"
    }
  ]
}
```
Parent is having update and shared permission and child is having insert and update permission. Package level permission is: insert-> none, update-> none, delete -> none

**Comment by aklish** [comment]
I have a hunch.  First thing to note is that SharePermission is failing on the parent.  SharePermission has no security expression of its own but rather uses the same permissions as the ReadPermission for the class. 

The check is technically failing because you are sharing the parent with the newly created child.  This invokes the ReadPermission on the parent (which is failing).

If you look at our tests for something similar, they look more like this:

```
mutation {
  author(ids: ["1"]) {
    edges {
      node {
        id
        books(op: UPSERT, data: {title: "Book Numero Dos"}) {
          edges {
            node {
              title
            }
          }
        }
      }
    }
  }
}
```

When referencing the parent (in this case author), we use the ids attribute whereas you use a filter.   

Normally when adding a child object to a parent, we don't check share permission on the parent directly if the user already navigated through the parent to get to the child (they can clearly read it already).  Since you navigated to the parent through the filter, it is bypassing this enhancement.

I'm still puzzled though why this failed because the user should be able to read parent (id=1), but for some reason the same check is failing.

Could you share your entities and permission checks?  It will help us create a meaningful test case to see if something else is going on.

**Comment by bappajubcse05** [comment]
```
@Entity
@Data
@Getter
@Setter
@AllArgsConstructor
@UpdatePermission(expression = "Prefab.Role.All")
public class Parent implements Persistable<UUID> {
    @Id
    @Type(type = "uuid-char")
    @GeneratedValue
    private UUID id;
    @NonNull
    @Column(unique = true, nullable = false)
    @Size(max = 10)
    private String parentName;
    @OneToMany(mappedBy = "parent", cascade = CascadeType.ALL)
    @JsonManagedReference
    private Set<Child> childs;
    
    public void addChilds() {
        if (this.getChilds() != null) {
            this.getChilds().forEach(c -> c.setParent(this));
        }
    }

    public Parent() {
    }

    @Override
    @Transient
    public boolean isNew() {
        return id == null;
    }
}

```
```
@Entity
@Getter
@Setter
@UpdatePermission(expression = "Prefab.Role.All")
@CreatePermission(expression = "Prefab.Role.All")
public class Child implements Persistable<UUID> {
    @Id
    @Type(type = "uuid-char")
    private UUID id;
    @Size(max = 200)
    private String childName;    
    @ManyToOne
    @JoinColumn(name = "parent_id")
    @JsonBackReference
    private Parent parent;
    
    public Child() {
    }

    @Override
    @Transient
    public boolean isNew() {
        return id == null;
    }
}

```
package level permission (Package-info.java):

```
@Include(rootLevel = true)
@DeletePermission(expression = "Prefab.Role.None")
@UpdatePermission(expression = "Prefab.Role.None")
@CreatePermission(expression = "Prefab.Role.None")
```

**Note: I am using Lombok.**

**Comment by aklish** [comment]
Thanks for sharing the classes.  I believe I understand things now.

To get this to work, you either need to make Parent shareable explicitly by adding SharePermission to it _*OR*_ you can change your query to be like:

```
  parent(ids: ["1"]) {
```

IMO, SharePermission behavior is not as crisp as it ought to be.  We should probably relax it so that it is not required to add a newly created item to an existing one under any circumstance.  I think that behavior would be good for Elide 5.0 (will file a ticket for it).  

SharePermission is not checked if you create an item _and_ attach it to an existing one _and_ navigated directly through the parent by ID.  This is pretty arbitrary.  Most people likely don't encounter this because they don't add items to something they found by filtering.

Let me know if this makes sense and if my solutions work for you.   I'll file the ticket to fix, but since it changes behavior for security related functions - I think this should be for elide 5.0

**Comment by bappajubcse05** [comment]
Hello @aklish,
I tried with these workarounds before logging the issue but unfortunately both didn't work for me.
Could you please suggest me some other workaround as I need to fix this ASAP.

**Comment by aklish** [comment]
I'll take your classes and create an example project.  If it works, I'll share.  If it doesn't work I will debug.

**Comment by aklish** [comment]
I was able to reproduce the issue and find the bug.  In my environment, I was able to make a tiny fix that resolves this.  

I need to add a test though.  Here is the patch if you want to build for yourself until I get out a proper fix:

```
diff --git a/elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java b/elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
index 90333624..15a336f9 100644
--- a/elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
+++ b/elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
@@ -1162,7 +1162,7 @@ public class PersistentResource<T> implements com.yahoo.elide.security.Persisten
             //         that newly created object within the context of the request. Thus, if any such action was
             //         required, the user would be forced to provide a UUID anyway.
             String id = dictionary.getId(getObject());
-            if (uuid.isPresent() && "0".equals(id)) {
+            if (uuid.isPresent() && ("0".equals(id) || "null".equals(id))) {
                 hashCode = Objects.hashCode(uuid);
             } else {
                 hashCode = Objects.hashCode(id);
```

**Comment by aklish** [comment]
FYI, this bug only happens if you use a non-primitive ID type.

**Comment by bappajubcse05** [comment]
Hello @aklish,

Could you please let me know the release timeline for this fix i,e, elide 5.0?

Thanks.

**Comment by aklish** [comment]
The fix is released in Elide 4.3.2

**Comment by bappajubcse05** [comment]
@aklish thank you so much.

**Comment by 19031987** [comment]
@aklish  the updated version did not help us still get the same issue , Could you please give us the sample json how you have tested the scenario ?

**Comment by aklish** [comment]
Note that you will still need to change your query to:
```
  parent(ids: ["1"]) {
```

Here is the unit test I added to Elide:
https://github.com/yahoo/elide/pull/761/files#diff-ca999420a09206b5f5f38225a9f6128e

Also, I manually tested a modified Elide Standalone to mimic your scenario.  Here is a branch on my repo that does this and verifies the fix works with 4.3.2

https://github.com/aklish/elide/tree/ReproduceIssue754

Hope that helps.

**Comment by aklish** [comment]
If you for my private repo and change the pom to point to 4.3.1, you'll see my new test in ElideStandaloneFails with the SharePermission error you had seen.

**Comment by bappajubcse05** [comment]
@aklish 
Thanks. It is working fine.
